version: "2.2"
services:
    VulnerableApp-base:
      image: sasanlabs/owasp-vulnerableapp:unreleased
      ports:
       - "9090:9090"

    VulnerableApp-jsp:
      image: sasanlabs/owasp-vulnerableapp-jsp:latest
      ports:
       - "9091:8080"

    VulnerableApp-facade:
      depends_on:
        - VulnerableApp-base
        - VulnerableApp-jsp
      image: sasanlabs/owasp-vulnerableapp-facade
      volumes:
       - ./templates:/etc/nginx/templates
      ports:
       - "80:80"
      environment:
       - NGINX_HOST=foobar.com
       - NGINX_PORT=80