name: Compile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: "5.1.5"
    - uses: leafo/gh-actions-luarocks@v4.0.0
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: build lua
      run: |
        luarocks install busted
        luarocks make
      working-directory: lua-modules
    - name: build node
      run: |
        npm install
        npm test
      working-directory: facade-app   
